### ISSUE TITLE
Open Graph issues

### ISSUE THREAD

**Issue by boardfish** [pawlean/nextpn#2]
https://realfavicongenerator.net/social/checker reports a few things in the Open Graph metadata for this site that could do with a change. That'll help the site show up better if shared to Facebook or LinkedIn. 

- image width/height are missing (og:image:width/height)
- no description
- Open Graph type should be "website" for the main site and "article" for blog posts

Mine's not yet perfect either, but I thought it'd be worth flagging up since it's easy to overlook. Hope it helps!

**Comment by pawlean** [comment]
Fixed, thanks for pointing this out Simon!
