### ISSUE TITLE
High resolution favicons

### ISSUE THREAD

**Issue by boardfish** [pawlean/nextpn#3]
https://realfavicongenerator.net reports that favicons for Chrome, Safari, etc. are missing. These are most often used for when a page is saved to your home screen or pinned tabs, so it might not be an issue. I'm fairly sure there are things out there that generate these favicons easily, though. You might be able to use the plain HTML realfavicongenerator gives you if you put the images somewhere that's publicly accessible.

**Comment by pawlean** [comment]
Fixed, thanks so much!
