### ISSUE TITLE
[BUG] Hover with Alphachannel

### ISSUE THREAD

**Issue by Cahllagerfeld** [pawlean/nextpn#73]
The hover-effect of the header-icons respects the alphachannel of the icons. (See gif for better explanation)

If its intended feel free to close (:

![screencast](https://user-images.githubusercontent.com/43843195/130239659-d7eac768-586c-4472-ba18-b6069e3972f3.gif)

**Comment by Cahllagerfeld** [comment]
[Oh it looks intended 😅 ](https://github.com/pawlean/nextpn/blob/8e1966e4d78cd5d59afb730b1f6855a1e89f6aba/components/socialmedia.js#L20)

**Comment by pawlean** [comment]
Hehe, sorry just seen this! Yes, for now. I do want to crate a re-write soon! Closing for now.
